// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: bids.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const createBid = `-- name: CreateBid :one
INSERT INTO bids (
  product_id, 
  bidder_id, 
  amount
) VALUES (
  $1, 
  $2, 
  $3
) RETURNING id, product_id, bidder_id, amount, created_at
`

type CreateBidParams struct {
	ProductID uuid.UUID `json:"product_id"`
	BidderID  uuid.UUID `json:"bidder_id"`
	Amount    float64   `json:"amount"`
}

func (q *Queries) CreateBid(ctx context.Context, arg CreateBidParams) (Bid, error) {
	row := q.db.QueryRow(ctx, createBid, arg.ProductID, arg.BidderID, arg.Amount)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getBidByProductId = `-- name: GetBidByProductId :many
SELECT id, product_id, bidder_id, amount, created_at FROM bids 
WHERE product_id = $1
ORDER BY amount DESC
`

func (q *Queries) GetBidByProductId(ctx context.Context, productID uuid.UUID) ([]Bid, error) {
	rows, err := q.db.Query(ctx, getBidByProductId, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bid
	for rows.Next() {
		var i Bid
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BidderID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighestBidByProductId = `-- name: GetHighestBidByProductId :one
SELECT id, product_id, bidder_id, amount, created_at FROM bids 
WHERE product_id = $1
ORDER BY amount DESC
LIMIT 1
`

func (q *Queries) GetHighestBidByProductId(ctx context.Context, productID uuid.UUID) (Bid, error) {
	row := q.db.QueryRow(ctx, getHighestBidByProductId, productID)
	var i Bid
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BidderID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
